# Generated by Django 5.0.7 on 2024-08-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Введите колличество просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
    ]
